accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('', views.pagepertama, name='pagepertama'),
    path('login/', views.pagelogin, name='pagelogin'),
    path('menu/', views.pagemenu, name='pagemenu'),
    path('logout/',views.logoutpage, name='logoutpage'),
]

bikinstory9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def pagelogin(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('accounts:pagemenu')
	else:
		form = AuthenticationForm()
	return render(request, 'pagelogin.html', {'form':form})

def pagepertama(request):
	return render(request, 'pagepertama.html')

def pagemenu(request):
	if request.user.is_authenticated:
		return render(request,'pagemenu.html')
	else:
		return redirect('accounts:pagelogin')

def logoutpage(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			logout(request)
	return redirect('accounts:pagepertama')

accounts/templates/pagelogin.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>WOWOWOW</title>
</head>
<style>
	body{
		text-align: center;
	}
</style>

<body>
	 <h1>Login</h1>
	 <form class="site-form" action="{%url 'accounts:pagelogin' %}" method="post">
	 	{% csrf_token %}
	 	<div id="flexbox-container">
	 	{{form.as_p}}
	 	</div>
	 	<input type="submit" value="Login">
	 </form>
</body>

accounts/templates/pagemenu.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>WOWOWOW</title>
</head>
<style>
	body{
		text-align:center;
	}
</style>

<body>
	<h1>Login berhasil</h1>
	{% if user.is_authenticated %}
	<h3>Welcome {{ user.username }}!</h3>
	<form class="logout-link" action="{%url 'accounts:logoutpage' %}" method="post">
		{% csrf_token %}
		<button type="submit">Logout</button>
	</form>
	{% endif %}
	
</body>

accounts/templates/pagepertama.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>WOWOWOW</title>
</head>
<style>
	body{
		text-align: center;
	}
</style>

<body>
	<h1>Silahkan Login</h1>
	{% if not user.is_authenticated %}
	<a href="{%url 'accounts:pagelogin' %}">Klik aje bro</a>
	{% endif %}
</body>